name: ci-jobs

on:
  pull_request:
    paths:
      - "Dockerfile"
  push:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  image-build:
    name: Build, Anchore scan image security test and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run make build-image image-scan
        run: make build-image image-scan image-push
  image-scan-push:
    name: Build, Anchore scan image security test and push
    runs-on: ubuntu-latest
    needs:
      - image-build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run make build-image image-scan
        run: make build-image image-scan image-push