name: ci-jobs

on:
  pull_request:
    paths:
      - "Dockerfile"
  push:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:  
  image-build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run make build-image
        run: make build-image
  
  image-scan:
    name: Anchore scan image security test
    runs-on: ubuntu-latest
    needs:
      - image-build
    steps:
      - name: Run make image-scan
        run: make image-scan

  image-push:
    name: Anchore scan image security test
    runs-on: ubuntu-latest
    needs:
      - image-build
      - image-scan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run make image-scan
        run: make image-push